#!/bin/sh
clear
source /usr/bin/pxn/scripts/defines.sh


echo
echo -e "$COLOR_LIGHTGRAY B${COLOR_BLACK}BLACK $COLOR_RESET"
echo -e "$COLOR_BLUE BLUE $COLOR_RESET"
echo -e "$COLOR_GREEN GREEN $COLOR_RESET"
echo -e "$COLOR_CYAN CYAN $COLOR_RESET"
echo -e "$COLOR_RED RED $COLOR_RESET"
echo -e "$COLOR_PURPLE PURPLE $COLOR_RESET"
echo -e "$COLOR_BROWN BROWN $COLOR_RESET"
echo -e "$COLOR_LIGHTGRAY LIGHT GRAY $COLOR_RESET"
echo -e "$COLOR_LIGHTGRAY D${COLOR_DARKGRAY}DARK GRAY $COLOR_RESET"
echo -e "$COLOR_LIGHTBLUE LIGHT BLUE $COLOR_RESET"
echo -e "$COLOR_LIGHTGREEN LIGHT GREEN $COLOR_RESET"
echo -e "$COLOR_LIGHTCYAN LIGHT CYAN $COLOR_RESET"
echo -e "$COLOR_LIGHTRED LIGHT RED $COLOR_RESET"
echo -e "$COLOR_LIGHTPURPLE LIGHT PURPLE $COLOR_RESET"
echo -e "$COLOR_YELLOW YELLOW $COLOR_RESET"
echo -e "$COLOR_WHITE WHITE $COLOR_RESET"
echo
